#!/usr/bin/env python
"""
moin - control MoinMoin Standalone server

If you want to use this to put standalone in daemon mode,
you also need moin.py which is the standalone moin script itself.
                      
@copyright: 2004-2005 Thomas Waldmann, Nir Soffer
@license: GNU GPL, see COPYING for details.
"""
import sys

# Path to MoinMoin package, needed if you installed with --prefix=PREFIX
# or if you did not use setup.py.
## sys.path.insert(0, 'PREFIX/lib/python2.3/site-packages')

# Add the path to moin.py directory 
## sys.path.insert(0, '/path/to/moin')

from MoinMoin.server import daemon
from moin import Config, run

script = daemon.DaemonScript(Config.name, run, Config)
script.run()

