
/*
 * Include this file in autogenerated XDR stub files, generated by
 * arpcgen, for use in Flume libraries.  Include all of the important
 * includes here.
 */
#ifndef _FLUME_RPC_H_
#define _FLUME_RPC_H_

#include "flume_sfs.h"

#endif /* _FLUME_RPC_H_ */
