
SRCDIR_LIBAMYSQL := srv/libamysql
OBJDIR_LIBAMYSQL := $(OBJDIR)/$(SRCDIR_LIBAMYSQL)

OBJDIRS     += $(OBJDIR_LIBAMYSQL)
SRV_INCLUDE += -I$(OBJDIR_LIBAMYSQL) -I$(SRCDIR_LIBAMYSQL)

LIBAMYSQL_OFILES := mystmt_ag.lo amysql.lo mtdispatch.lo mystmt.lo web.lo 

LIBAMYSQL_OBJS := $(foreach ofile, $(LIBAMYSQL_OFILES), \
				$(OBJDIR_LIBAMYSQL)/$(ofile) )

LIBAMYSQL_LA := $(OBJDIR_LIBAMYSQL)/libamysql.la

LIBAMYSQL_HEADERS := $(OBJDIR_LIBAMYSQL)/mystmt_ag.h


##-----------------------------------------------------------------------
##
##  Autogenerated DB interface files
##

$(OBJDIR_LIBAMYSQL)/%_ag.h: $(SRCDIR_LIBAMYSQL)/%_ag.pl
	@echo "+  gen: $@"
	@mkdir -p $(@D)
	$(V)$(PERL) $< -h > $@

$(OBJDIR_LIBAMYSQL)/%_ag.C: $(SRCDIR_LIBAMYSQL)/%_ag.pl \
			    $(OBJDIR_LIBAMYSQL)/%_ag.h
	@echo "+  gen: $@"
	@mkdir -p $(@D)
	$(V)$(PERL) $< -c > $@

##
## End autogenerated DB interface files
##
##-----------------------------------------------------------------------

##-----------------------------------------------------------------------
##
## Default build rules for .C, .T files...

objdir := $(OBJDIR_LIBAMYSQL)
srcdir := $(SRCDIR_LIBAMYSQL)

include make/srv.mk

##
##-----------------------------------------------------------------------

##-----------------------------------------------------------------------
##
## Make the appropriate la / library at the end of the day
##

$(LIBAMYSQL_LA): $(LIBAMYSQL_OBJS)
	@echo "+   ld: $@"
	$(V)$(LT_LD) $(FLUME_RPATH) -shared -o $@ $^ 

##
##-----------------------------------------------------------------------

.PRECIOUS: $(OBJDIR_LIBAMYSQL)/%.C $(OBJDIR_LIBAMYSQL)/%.h

all: $(LIBAMYSQL_HEADERS) $(LIBAMYSQL_LA)

install-libamysql: \
	install-libamysql-lib

install-libamysql-lib: $(LIBAMYSQL_LA)
	@echo "+ inst:" `basename $<` "-> $(FLUMELIB)"
	@mkdir -p $(FLUMELIB)
	$(V)$(LT_INSTALL) $(LIBMODE) $< $(FLUMELIB)
